version: '2'
services:
  innovate-admin:
#    image: mikeyboom/innovate-admin
    image: registry.cn-shenzhen.aliyuncs.com/mikey/innovate-admin:latest
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - /root/mikey/MIKEY:/home/mikey/MIKEY
    environment:
      - spring.profiles.active=prod
